### ISSUE TITLE
Screenshots don't work when context menu is open

### ISSUE THREAD

**Issue by uncertainquark** [elementary/screenshot#130]
The keyboard shortcuts to take a screenshot doesn't work when a context menu is opened in the files app say. It also doesn't work with the screenshot app opened and set to take a shot manually (with or without a delay). In the following image for example, I tried to screenshot the Files app window and it didn't work and so I had to take a picture to show.  

![photo_2019-05-14_18-02-37](https://user-images.githubusercontent.com/22585732/57698619-adc20100-7673-11e9-96b3-1b99de77ced1.jpg)

**Comment by peteruithoven** [comment]
There is a existing issue regarding keyboard shortcuts not working when a menu is open: https://github.com/elementary/gala/issues/500
(Gala takes the screenshots when keyboard shortcuts are used)

With the Screenshot app, with a delay and set to take a screenshot of the current window even when I open a context menu, it does take a screenshot it just doesn't include the context menu. I don't think this is something Screenshot can fix. If it is fixable we should probably fix it in Gala since that will be responsible for taking the screenshots in the future: https://github.com/elementary/screenshot/issues/103

With the Screenshot app, with a delay and set to take a screenshot of the whole screen just works fine. 

So your issue is partly invalid and partly a duplicate I'm afraid?

**Comment by jeremypw** [comment]
I did submit a possible solution some time ago (#19) but it was considered too 'hacky' to merge.

**Comment by danrabbit** [comment]
I’m going to close this as “Out it Scope” since neither of these issues can be solved within the scope of this code base.

As Peter pointed out, future versions of screenshot will use an API provided by the window manager to take screenshots, so including child windows like menus should be possible then.

As for accepting keyboard shortcuts while menus are open, it’s my understanding that this is a limitation of X11 and it is solved in Wayland. But regardless this is not solvable by screenshot and requires work in the window manager.
