### ISSUE TITLE
[Feature Suggestion] Area Size in Pixels

### ISSUE THREAD

**Issue by a-tokarev** [elementary/screenshot#137]
It would be very useful to display **area size in pixels** (like, 624x817px) hint in the process of capturing. Thank you!

**Comment by peteruithoven** [comment]
I think, because of https://github.com/elementary/screenshot/issues/103, that we should implement this in the [Gala](https://github.com/elementary/gala/). Currently both Gala and the Screenshot tool implement selection area's:
- https://github.com/elementary/screenshot/blob/master/src/Widgets/SelectionArea.vala
- https://github.com/elementary/gala/blob/master/src/Widgets/SelectionArea.vala

@a-tokarev could you open a new issue in the [Gala repo](https://github.com/elementary/gala/)? Instead of transferring the issue to Gala I'd like to keep this issue here so people can find it.

**Comment by a-tokarev** [comment]
@peteruithoven,
[done](https://github.com/elementary/gala/issues/568).
