### ISSUE TITLE
Wont start.

### ISSUE THREAD

**Issue by demonicPbunny** [elementary/screenshot#221]
Distro: Manjaro

** (io.elementary.screenshot:10150): ERROR **: 15:17:28.099: ScreenshotBackend.vala:37: Couldn't get dbus proxy: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Screenshot was not provided by any .service files

**Comment by dogonthehorizon** [comment]
I'm seeing this behavior as well when upgrading to `6.0.0`. I'm using ArchLinux and can confirm that when downgrading to `pantheon-screenshot-1.7.1` the tool works as expected.

Based on what I can gather from [this platform changes post](https://blog.elementary.io/platform-changes-in-elementary-os-6/) it appears that the screenshot tool is now delegating work to the window manager.

Unfortunately I'm not familiar enough with DBus to understand who or what might provide the Screenshot service. I understand I'm likely consuming parts of Pantheon in an unsupported way, but any pointers to understanding the mechanics of this would be helpful. I'm happy to contribute learnings in a wiki somewhere when we've resolved the issue :)

**Comment by davidmhewitt** [comment]
I would suggest installing "d-feet" and checking to see if something is providing the necessary d-bus interfaces for the screenshot tool. Neither comment here even states if you're using Gala as the window manager. See the screenshot below. You can see `gala` is providing an `org.gnome.Shell` bus and an `org.gnome.Shell.Screenshot` bus, both with the necessary `/org/gnome/Shell/Screenshot` interfaces, with associated screenshot methods.

![Screenshot from 2021-09-06 15 16 58](https://user-images.githubusercontent.com/3372394/132238102-ae7a3f6b-dc78-4d09-a97f-2f1e5e2d3ea8.png)

If nothing is providing those buses, the next question would be to think about why. I.e. are you running a different window manager that doesn't provide GNOME compatible screenshot interfaces

**Comment by dogonthehorizon** [comment]
@davidmhewitt fantastic, I wasn't familiar with `d-feet`, thank you! I don't appear to have anything providing `org.gnome.Shell` _or_ `org.gnome.Shell.Screenshot`.

> I.e. are you running a different window manager that doesn't provide GNOME compatible screenshot interfaces

Yes, when I said I'm likely running screenshot in an unsupported way I should have further clarified that I'm using my own window manager and running as little of gnome/gala as possible. In particular, I'm using XMonad and installing the pieces of Gala that I find myself using repeatedly (like screenshots).

If you'd indulge me a little more, what is the relationship between the window manager and these interfaces? Does XMonad, in this case, need to tell DBus that it implements these interfaces? Could you point me towards the relevant documentation so I can understand this more?

**Comment by davidmhewitt** [comment]
The screenshot tool doesn't actually do much itself, it's kind of a frontend to ask the window manager to take a screenshot. This will be necessary in future where we're using Wayland because a random application won't be able to take a screenshot of the desktop or of other windows. The security in Wayland means an application only has access to its own windows, and the only thing that has access to the contents of the entire screen is the Compositor/Window Manager.

So, without the necessary interfaces to talk to the window manager and ask it to take a screenshot, the elementary screenshot tool is useless. So useless in fact, it crashes to save you the trouble of trying to use it :laughing: 

I doubt XMonad provides any GNOME compatible screenshot interfaces, so I'm afraid it won't be a useful tool for you unless you're running Gala/GNOME or another compositor that happens to provide a GNOME screenshot interface.

**Comment by dogonthehorizon** [comment]
Excellent, thanks again @davidmhewitt. For the time being I'll keep using the older version of the tool and figure out more of this DBus business as I have time. I've also add some notes [here](https://wiki.archlinux.org/title/Pantheon#Missing_DBUS_Services) to hopefully mitigate some churn in the issue trackers for elementary projects :) Please let me know if I've misrepresented anything so I can fix it promptly!

I won't speak for @demonicPbunny but this issue can be closed as far as I'm concerned.

**Comment by davidmhewitt** [comment]
@dogonthehorizon I don't think I'd class it as "many Pantheon services". I think the only difference in Gala's responsibility model you'll find compared to previous releases is with the Screenshot tool. The other features added to Gala during the 6.0.0 release are touchpad gestures, which didn't exist prior to 6.0.0 and are a feature of the window manager itself anyway, and some accessibility features were moved from gnome-settings-daemon to the window manager because they were deprecated in g-s-d.

Other than that, the window manager has the same responsibilities as it did before.

Hopefully the words on the wiki help someone with the same issue though, so thanks for that!

I'll close this issue, and if @demonicPbunny has this issue while running Screenshot on Gala/GNOME, please let me know and we can re-open and investigate more.
